---
# application part
- hosts: application
  become: yes
  tasks:
    - name: Install Python3
      state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
    
    - name: Install MySQL
      apt: 
        name: mysql-server
        state: present

# Database Part
- hosts: Database
  become: yes
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        sate: present
  