---
- hosts: application
  become: yes
  tasks:
    - name: Install Python3 on databse & application VM
      ansible.builtin.apt:
        name: python3
        state: present

    - name: Install Docker on database & application VM
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Install MySQL on databse & application VM
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Install MySQL Client on database & application VM
      ansible.builtin.apt:
        name: mysql-client
        state: present
