- hosts: all_servers
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes


    - name: Install Python3 on database & application VM
      ansible.builtin.apt:
        name: python3
        state: present

    - name: Install Python3-pip (Optional)
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install Docker on database & application VM
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Install MySQL Server on database & application VM
      ansible.builtin.apt:
        name: mysql-server
        state: present

    - name: Install MySQL Client on database & application VM
      ansible.builtin.apt:
        name: mysql-client
        state: present

